### ISSUE TITLE
libstdc++.so.6: cannot open shared object file

### ISSUE THREAD

**Issue by lukechilds** [frol/docker-alpine-glibc#17]
Great work on this!

I'm getting:

```
$ docker run lukechilds/vertcoind:alpine -version
vertcoind: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

Precompiled binary from here: https://github.com/vertcoin/vertcoin/releases/tag/v0.11.1.0

**Comment by frol** [comment]
It states clearly that you are missing `libstdc++.so.6`. This library is part of C++ runtime and you have to get it somewhere since it is not a part of glibc by no means. Sometimes, musl-based libraries work, so you can give Alpine package `libstdc++` a try (`apk add libstdc++`) if that crashes the app, you will have to fetch the library from glibc-based Linux distribution, e.g. Debian, Ubuntu, Arch Linux...

It is not an issue of this image, so I close it, but you are welcome to share your findings and ask other questions.

Good luck!

**Comment by lukechilds** [comment]
Sorry, didn't realise it was unrelated to this package, I have no idea what I'm doing. 😂

Thanks for you help!

**Comment by holms** [comment]
@lukechilds  any chance to find that package and integrate it into alpine :)?
